---

- name: Motor Driver Test Playbook
  hosts: THUNDERBOTS_HOSTS

  tasks:

    - debug:
        msg: "[Robot ID = {{ inventory_hostname }}]"
      tags: always

    - name: Start Motor Driver Test Process
      block:

        - name: Stop Services
          become: true
          become_method: sudo
          ansible.builtin.systemd:
              name: "thunderloop.service"
              masked: no
              daemon_reload: yes
              state: stopped
          tags: always

        - name: Delete motor_driver_test binary under ~/thunderbots_binaries
          file:
            state: absent
            path: ~/thunderbots_binaries/motor_driver_test
          become_method: sudo
          become: true
          register: result

        - debug:
            msg: "{{ansible_search_path}}"
          tags: always

        - name: Sync Binary
          ansible.posix.synchronize:
            src: ../../services/motor_driver_test
            dest: ~/thunderbots_binaries/
            verify_host: yes
            recursive: yes
            copy_links: yes
          tags: always

